import localFont from "next/font/local";
import "../styles/globals.css";
import ClientLayout from "./ClientLayout";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Header from "@/components/HomePage/Header";

// Define custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for your application
export const metadata = {
  title: "Jenii - Jewelry App",
  description: "Generated by create next app",
};

// Layout component (Server Component)
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientLayout>
          <Header/>
          {children}
          </ClientLayout> {/* Client logic here */}
        <ToastContainer position="top-right" autoClose={5000} hideProgressBar={false} closeOnClick draggable pauseOnHover />
      </body>
    </html>
  );
}
